name: adaptive_design
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^0.13.5
  intl: ^0.18.1
  form_field_validator: ^1.1.0
  multiselect: ^0.0.4
  fl_animated_linechart: ^1.1.9
  fl_chart: ^0.55.2
  syncfusion_flutter_charts: ^18.4.49

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/ui/common/logos/logo2.png

